# Generated by Django 5.2.1 on 2025-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('applicant_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ifsc', models.CharField(db_index=True, max_length=11)),
                ('credit', models.FloatField(default=0.0)),
                ('debit', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('city', models.CharField(max_length=50)),
                ('branch', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_records',
                'ordering': ['applicant_no'],
            },
        ),
    ]
